### ISSUE TITLE
Please Support Error Trace

### ISSUE THREAD

**Issue by wenshenjun** [nest-x/nestx-log4js#449]
https://github.com/nest-x/nestx-log4js/blob/4512213adca4207f18b7f80a2400f4277eda3b84/packages/core/src/log4js.classes.ts#L37-L40

Just miss trade paramter.

**Comment by sosohime** [comment]
Myleader, please review this PR
#451

**Comment by aquariuslt** [comment]
@wenshenjun release v1.4.0 fixed

**Comment by wenshenjun** [comment]
@sosohime  @aquariuslt  Thanks, Awesome!

**Comment by wenshenjun** [comment]
@sosohime  error msg & error in the same line will be better.

like this,
https://github.com/log4js-node/log4js-node/blob/f8d46a939279c0ab4efc8bb5f0478c4b0949a4cf/test/tap/logging-test.js#L33

https://github.com/nest-x/nestx-log4js/pull/451#r605383764_

**Comment by sosohime** [comment]
I saw the implementation of log4js, its in same line
@aquariuslt what you think about this, myleader
this lib is log4js plugin of nestjs, so we may need to maintain log4js performance rather than nestjs logging?
Based on the above reasons, it should be amended as`this.logger.error(message, trace); `

**Comment by aquariuslt** [comment]
> I saw the implementation of log4js, its in same line
> @aquariuslt what you think about this, myleader
> this lib is log4js plugin of nestjs, so we may need to maintain log4js performance rather than nestjs logging?
> Based on the above reasons, it should be amended as`this.logger.error(message, trace); `

yes PR welcome.

**Comment by aquariuslt** [comment]
for the practice in Java(logback), implement custom layout and custom layout options `replace(p){r, t}` and replace multi-line stack trace's `\n` to other placeholder in sameline is friendly for remote service logger. 

but log4js-node not support currently. 

see http://logback.qos.ch/manual/layouts.html



replace(p){r, t}

```
Replaces occurrences of 'r', a regex, with its replacement 't' in the string produces by the sub-pattern 'p'. For example, "%replace(%msg){'\s', ''}" will remove all spaces contained in the event message.

The pattern 'p' can be arbitrarily complex and in particular can contain multiple conversion keywords. For instance, "%replace(%logger %msg){'\.', '/'}" will replace all dots in the logger or the message of the event with a forward slash.
```

**Comment by aquariuslt** [comment]
> @sosohime error msg & error in the same line will be better.
> 
> like this,
> https://github.com/log4js-node/log4js-node/blob/f8d46a939279c0ab4efc8bb5f0478c4b0949a4cf/test/tap/logging-test.js#L33
> 
> [#451 (comment)](https://github.com/nest-x/nestx-log4js/pull/451#r605383764)_

v 1.5.0 fixed
